import LocalizedStrings from "react-native-localization";

export default new LocalizedStrings({
  en: {
    aed: "AED",
    yes: "Yes",
    no: "No",
    arabic_aed: "درهم",
    service_charges: "Packing/UnPacking Charges",
    packing_services: "Packing Service",
    unpacking_services: "Unpacking Service",
    arabic_cash_on_delivery: "نقدا عند التسليم",
    arabic_invoice: "فاتورة",
    language: "Language",
    cheap_and_smart_Solutions:
      "Cheap & smart solution\n          for your move.",
    sign_in: "Sign In",
    create_account: "Create Account",
    mobile_verification: "Mobile Verification",
    we_will_send_you:
      "We will send you a One Time Password\n               on the mobile number",
    one_time_password: "One Time Password",
    already_have_account: "Already have an account? Sign In",
    sign_up: "Sign Up",
    notes_description:
      "Feel free to describe any other instructions or requirements you may have.",
    on_the_mobile_number: "on the mobile number",
    enter_mobile_number: "Enter Mobile Number",
    get_code: "GET Code",
    code_verification: "Code Verification",
    enter_code_sent_to: "Enter the Code sent to",
    didnt_receive_code: "Didn't receive the code?",
    resend_code: "RESEND CODE",
    verify_proceed: "VERIFY & Proceed",
    registration_details: "Registration Details",
    create_new_account: "Create a new account",
    please_accept_terms_and_conditions: "Please accept terms and conditions",
    first_name: "First Name",
    last_name: "Last Name",
    enter_first_name: "Enter First Name",
    enter_last_name: "Enter Last Name",
    email: "E-mail",
    password: "Password",
    confirm_password: "Confirm Password",
    customer: "Customer",
    driver: "Driver",
    enter_vehicle: "Enter Vehicle",
    enter_vehicle_plate_no: "Enter Vehicle Plate No",
    vehicle_name: "Vehicle Name",
    vehicle_number_plate: "Plate No",
    i_agree_to_the_movaz: "I agree to Movaz ",
    terms_and_conditions: "Terms & Conditions",
    eg_jhon: "e.g John",
    eg_doe: "e.g Doe",
    example_email: "example@gmail.com",
    enter_password: "Enter Password",
    retype_password: "Re-type Password",
    email_or_phone: "Email or Phone",
    welcome_back: "Welcome Back!",
    sign_in_to_continue: "Sign in to Continue",
    email_or_phone_971: "Email or Phone (971)",
    forgot_password: "Forgot Password?",

    Im_a_Driver: "I'm a Driver",
    dont_have_an_Account: "Don't have an account yet?",
    driver_earnings: "Driver Earnings",
    driver_rating: "Driver Rating",
    total_payable: "Total Payable",
    paid_amount: "Paid Amount",
    balance: "Balance",
    sub_total: "Sub Total",
    vat: "Vat",
    total_trips_amount: "Total Trips Amount",
    comission_inclusive_vat: "Comission (inclusive Vat)",
    total_balance: "Total Balance",
    customer_signature: "Customer Signature",
    please_sign_in_the_space_below: "Please sign in the space below",
    order_delivered: "Order Delivered",
    order_id: "Order ID",
    amount: "Amount",
    items_type: "Moving Size",
    pickup_date: "Pick-up Date",
    pickup_earliest_date: "Pick-up Date/Time",
    pickup_latest_date: "Pick-up Time",
    attachments: "Attachments",
    start_trip: "Start Trip",
    total_amount: "Total Amount",
    amount_received: "Amount Received",
    change_back: "Change Back",
    continue_: "Continue",
    cash_on_delivery: "Cash on Delivery",
    reached_on_pickup: "Reached at Pick-up",
    reached_on_delivery: "Arrived",
    full_name: "Full Name",
    emirate: "Emirate",
    mobile: "Mobile",
    change_password: "Change Password",
    update_profile: "Update Profile",
    reviews: "Reviews",
    my_profile: "My Profile",
    reviews_and_comments: "Reviews and Comments",
    log_out: "Log Out",
    history: "History",
    customer_paid: "Customer paid (Cash)",
    company_fee: "Company Fee",
    your_earnings: "Your Earnings",
    items: "Items",
    vehicle: "Vehicle",
    vehicle_registration: "Vehicle Registration",
    order_process_history: "Order Process History",
    about_us: "About Us",
    about_us_heading: "About Us",
    help: "FAQ's",
    order_completed: "Order Completed",
    order_is_successfull: "Your Order is Successful!",
    order_completed_message:
      "\n  Thank you for using Movaz services.\nWe will send you a price quote in a few minutes.\n\n",
    back_to_home: "Home Page",
    call_support: "Call Support",
    email_support: "Email Support",
    cancel: "Cancel",
    select_pickup_adddress: "Confirm Address",
    select_delivery_adddress: "Confirm Address",
    upload_pictures: "Upload Pictures",
    select_items_type: "Select Size",
    select_pickup_date_and_time: "Select Pick-up Date & Time Range",
    upload_pictures_quote: "Include all photos for a cost-effective quote",
    pickup_date_and_time: "Pick-up Date & Time",
    notes: "Instruction",
    notes_or_instructions: "Notes or Instructions",
    request_order: "Book & Live-Track",
    faqs: "Frequently Asked Questions",
    my_orders: "My Orders",
    order_details: "Order Details",
    total: "Total",
    process_history: "Process History",
    payment_cards: "Payment Cards",
    payment_methods: "Payment Methods",
    comments_reviews: "Comments & Reviews",
    change_your_password: "Change Your Password",
    enter_new_password: "Enter New Password",
    enter_current_password: "Enter Current Password",
    new_password: "New Password",
    confirm_new_password: "Confirm New Password",
    passwords_do_not_match: "Passwords do not match",
    enter_name: "Enter Name",
    enter_email: "Enter Email",
    save_changes: "Save Changes",
    order_history: "Order History",
    view_order: "View Order",
    support: "Support",
    please_provide_pin: "Please provide Pin Number",
    please_select_emirate: "Please Select Emirate",
    mobile_already_exists:
      "Mobile Number already Exists! Please login or forget password to use the app",
    mobile_does_not_exists: "Mobile Number does not Exists!",
    new_user_registered: "New User registered Successfully!",
    please_enter_mobile_number: "Please enter mobile number",
    please_enter_valid_mobile_number: "Please enter valid mobile number",
    please_enter_mobile_number_with_country_code:
      "Please enter valid mobile number with country code",
    Im_customer: "I'm a Customer",
    invalid_username_or_password: "Invalid Username or Password",
    new_order: "New Order",
    on_hold: "On Hold",
    in_process: "Under Process",
    ready_for_dispatch: "Ready for Dispatch",
    on_the_way_for_pickup: "On the way for Pick-up",
    moving_for_Delivery: "Moving for Delivery",
    delivered: "Delivered",
    profile_updated_successfully: "Profile Updated Successfully!",
    get_directions: "Get Directions",
    please_select_items_type: "Please Select Items Type",
    please_select_pickup_date: "Please Select Pick-up date",
    please_select_pickup_start_time: "Please Select Pick-up start time",
    please_select_pickup_end_time: "Please Select Pick-up End Time",
    pickup: "Pick-up",
    pickup_address: "Pick-up Address",
    dropoff_address: "Delivery Address",
    dispatch: "Dispatched",
    image_library: "Image Library",
    take_picture: "Take a Picture",
    choose_option: "Choose Option",
    accept: "Accept",
    track_order: "Track Order",
    status: "Status:",
    price: "Price:",
    view_details: "View Details: ",
    invoice: "Invoice",
    connect_via_social: "Connect via Social",
    invoice_is_downloaded: "Your Order Invoice\nis downloaded",
    go_to_directory: "Go to Directory:",
    forgot_your_password: "Forgot Your Password?",
    enter_mobile_number_recover_password: "Enter your mobile number",
    // enter_mobile_number_recover_password: 'Enter your mobile number to\nrecover your password',
    collected_amount: "Collected Amount",
    accept_selection: "Accept Selection",
    earliest_pickup_date: "Earliest Pick-up Date",
    building_street: "Building/Street",
    apartment_villa: "Apartment/Villa No.",
    drop_off_details: "Drop-off Details",
    pickup_details: "Pick-up Details",
    comments: "Comments",
    submit: "Submit",
    completed_orders: "Completed Orders",
    active_orders: "Active Orders",
    password_updated_successfully: "Password Updated Successfully",
    profile_image_updated_successfully: "Profile Image Updated Successfully!",
    error_while_updating_the_image: "Error while updating the image!",
    order: "Order #",
    cancelled: "Cancelled",
    under_process: "Under Process",
    dispatched: "Dispatched",
    completed: "Completed",
    requested: "Requested",
    settings: "Settings",
    portal: "Wallet",
    orders: "Orders",
    view: "View",

    please_enter_dropoff_apartment: "Please enter drop-off Apartment/Villa No",
    please_enter_dropoff_building: "Please enter drop-off Building/Street",
    please_enter_pickup_apartment: "Please enter pick-up Apartment/Villa No",
    please_enter_pickup_building: "Please enter pick-up Building/Street",
    about_us_first_heading: "Movaz - The pioneer of Transport Technology",

    about_us_first_paragraph:
      "Movaz is the 1st smart transport platform in the UAE that provides a unique combination of flexible logistics solutions & state-of-the-art technology that can increase efficiency, improve customer experience & reduce the environmental footprint of transportation.\nBy connecting our customers with our trusted partners, we meet the increasing demands for fast, low-cost & extraordinary transport experiences. For the benefit of businesses, consumers & the environment.",
    about_us_second_heading: "The need for innovation ",
    about_us_second_paragraph:
      "Good ideas are usually born out of problems that need to be solved. Movaz is no exception. Living in Dubai as an expat comes with its perks, as well as, the hassle of shifting houses & finding reliable, professional & low-cost movers & carriers. So, our idea came as an on-demand transport service that enables drivers with trucks & other transport vehicles to connect with people & businesses with deliveries, supported by live-tracking & smart logistic solution that reduces cost & waste.",
    about_us_third_heading: "The beginning of an era",
    about_us_third_paragraph:
      "Transparency & control of how goods are transported & delivered are the ultimate goal of Movaz towards its customers, by enabling the ApS (advanced planning & scheduling) & the live-tracking systems, we create the perfect & modern business model that provides our customers with a hassle-free, low-cost & eco-friendly experience.",
    about_us_fourth_heading: "Movaz - services for people & businesses",
    about_us_fourth_paragraph:
      "• We support our services with our state-of-the-art technology, providing full transparency & control of your logistics.\n\n • We have supporters on standby to assist if it is needed.\n\n • We certify and manage the quality of all drivers & riders who are at least 21 years of age & have 100% clean criminal records.\n\n• Anyone can easily make an order on our app or Website for fast, safe and low-cost delivery with live-tracking all the way.\n\n",
    first_paragraph:
      "                     These general terms & conditions for customers determine the terms & conditions that apply to all customers of Movaz.\n\nExceptions to these Terms & Conditions may be stipulated in individual agreemnets, which will at any time take precedence over these Terms & Conditions.",
    the_service_provider_is: "The Service Provider is:",
    first_condition: "1. Provider of the Service:",
    movaz_system_aps: "Movaz Logistics",
    support_email: "support@movaz.ae",
    second_condition: "2. The Service:",
    second_condition_details:
      "Movaz is an online platform & application that mediates contact between customers & partners, so that Movaz customers can have goods transported in UAE. The purpose of Movaz service is to ensure that the user of the platform can have goods transported by the following means of transport:\n\n1.	Motorbike or Passenger car\n2.	Van or pickup\n3.	Lift trolley    \n4.	Refrigerated Van\n\nCustomers are responsible for the goods being transported in the chosen means of transport. Partners who have been approved by Movaz will then be granted the rights and obligations arising from the Partner Terms. Movaz Platform enables our customers to send a request to Partners, who can then accept the shipment. Once the Partner has accepted the transport in question, information is exchanged, including names of both Partner and customer, type of vehicle, real-time location, addresses, instructions and so on.",
    third_condition: "3. Registration:",
    third_condition_details:
      "Customers wishing to register as users and use Movaz Platform must provide the following information:\n\n1.	Name\n2.	Mobile phone number and email.\n\nCustomers must be at least 18 years old to be registered with Movaz. People who have registered on Movaz Platform as customers will receive a personal account with a password. The registration with Movaz is personal and may not be used by anyone other than the customer.",
    forth_condition: "4. Transport of Goods:",
    forth_condition_details:
      "Movaz Platform allows the customers to send a transport request to one of our Partners. Our clients can send a request for transport here and now, or they can enter the date and time of the desired transport.\n\nThe customer has the full responsibility to inform about the correct description & number of the items in connection with ordering.\n\nMovaz enters into the contract with the customer and then brings the customer into contact with one of our partners by sending the customer’s request to partners in the area. Collection of the  goods at the desired time presupposes that a partner accepts the request.\n\nPartners have, at their discretion, the right to accept or reject a request for transportation.\n\nCustomers can choose that the goods may be placed outside the proven address.In that case, they must clearly state this in connection with the order. When the goods are placed according to the customer’s indication, the delivery is considered to have taken place, and the Partner notifies via the application. Thereafter, the risk of the goods is considered to have been transferred to the  customer & the goods are no longer covered by Movaz.",
    fifth_condition: "5. Delivery:",
    fifth_condition_details:
      "When goods are considered delivered to the right recipient,customer’s will be notified & obliged to ensure that the customer himself - or another authorized recipient of the goods - is present at the address designated by the customer as the correct place of delivery at the time of the Partner's arrival. However, this does not apply if the customer has given consent for the goods to be placed outside.\n\nIf there is no authorized recipient present at the address designated as the correct place of delivery, the Partner must try to contact the customer in order to agree on the terms of an alternative delivery. In this situation, the customer will be obliged to pay for the additional costs associated with such alternative delivery. However, this does not apply if the customer has given consent for the goods to be placed outside.\n\nIf the partner is unable to get in touch with the customer, the Partner is entitled to place the goods in front of the address after a waiting period of 15 minutes at the place of delivery. the risk for the goods must be considered transferred to the customer..\n\nOnce items are delivered, customers are required to submit their digital signature providing digital proof-of-delivery.",
    sixth_condition: "6. Rating of Partners:",
    sixth_condition_details:
      "Movaz uses a rating system where the partner/driver is rated by the customer  on a scale from 1 to 5 stars, which represents the partner’s/driver’s overall performance as follows:\n\n1.	Dissatisfied\n2.	Needs improvement\n3.	Satisfying\n4.	Good\n5.	Excellent\n\nCustomers should note that a partner/driver who does not maintain a running average rating of 4.5 or above will be assessed by Movaz & will then decide whether Movaz wishes to continue the partnership. The partner/driver will be excluded from  Movaz Platform if Movaz does not wish to continue the collaboration.",
    seventh_condition: "7. Payment:",
    seventh_condition_details:
      "   •   Payments made are non-refundable.\n   •   The customer has to provide Movaz with full details & description of the order, including, but not strict to; all Photos/description of the actual shipment or any further shipments to be added later. In case of failure to do so, Movaz reserves the right to change the price accordingly or cancel the order.\n\n\nAny complaint about a completed transport or its settlement must be submitted within 24 hours after the transport is completed by email to ",
    eighth_condition: "8. Personal Data Policy:",
    eighth_condition_details:
      "Movaz collects and processes a number of information about the customer, including in connection with the registration of the customer on Movaz Platform.\nIn connection with registration, customers expressly consents to Movaz processing & storing the information in accordance with the\nData Protection Ordinance (2016/679) of 27 April 2016 (the “Data Protection Act”),\ncf. separate personal data policy. Movaz is the data controller for this processing and processing of personal data is carried out in accordance with good data processing practice in accordance with the Data Protection Act.Movaz does not pass on customer’s information to another company for marketing purposes. Movaz does not use the information on behalf of another company for marketing purposes unless the customer has given his express consent.",
    ninth_condition: "9. Default:",
    ninth_condition_details:
      "In the event that the customer does not comply with the obligations arising from these Terms of Business, Movaz is entitled to immediately exclude the customer from the Movaz Platform.\n\nIn particular, Movaz is entitled to exclude the customer from the Movaz Platform if:\n\n1.	The customer exhibits aggressive, harassing or degrading behaviour.\n2.	The customer does not comply with applicable law, including in particular the Penal Code, the Firearms Act and the Narcotic Drugs Act.\n3.	In case of non-payment.\n\nMovaz must immediately after an exclusion, notify the customer via e-mail to the customer’s associated e-mail address. However, Movaz is not obliged to justify the exclusion.",
    tenth_condition: "10. Gift Cards and Discount Coupons:",
    tenth_condition_details:
      "Movaz can make available gift cards or discount coupons that are used as consideration to the payment to Movaz, for example in connection with fees. A gift card can be used to fully or partially cover a payment, while a discount coupon reduces the amount that the customer has to pay for a particular transaction.\n\nGift cards or discount coupons do not reduce the amount received by the Partner, as the difference between the amount before and after the use of the gift card or discount coupon is refunded by Movaz.\n\nGift cards or discount coupons cannot be replaced in the event of loss or theft and cannot be used after a possible expiration date.",
    eleventh_condition: "11. Disclaimer & limitation of liability:",
    eleventh_condition_details:
      "The use of Movaz Platform is at the customer’s own risk.\n\nThe information & recommendations received by the customer on Movaz Platform are for informational purposes only and do not constitute advice.\n\nMovaz is not responsible for the following:\n\n1.	Inaccurate content or errors in the Movaz Platform, such as typing errors or unintentional functions.\n2.	Personal injury or property damage that occurs at a time when the goods are not considered to be in Movaz possession,\n3.	Behaviour or actions of partners or other customers.\n4.   Movaz do not accept liabilities for goods that were confiscated, seized,removed or damaged by the Police, Customs Authorities or other government agencies from the origin to destination. Normal wears & tears, natural or gradual deterioration and changes caused by the atmospheric conditions and other moulds, rusting and other infestation.\n5. We are not liable as well for any delays of transit for such reason like:weather, or environmental accident or any machinery malfunction.\n6.  Customers & partners bear the sole liability of inspecting item before the pickup &/or any damages that may occur during transportation.",
    tweleveth_condition: "12. Amendment of the Terms & Conditions:",
    tweleveth_condition_details:
      "Movaz may at any time and without prior notice change these Terms of Business and discontinue the service by notifying the  customer via email to the  customer’s associated email address.\n\nIn the event of changes to these Terms and Conditions,customers will be notified and any use of  Movaz Platform by the customer will thereafter be deemed an acceptance of these Terms.",
  },

  ar: {
    aed: "درهم",
    yes: "نعم",
    no: "لا",
    arabic_aed: "درهم",
    packing_services: "خدمة التغليف",
    service_charges: "رسوم التعبئة / التفريغ",
    unpacking_services: "خدمة التفريغ",
    arabic_cash_on_delivery: "نقدا عند التسليم",
    arabic_invoice: "فاتورة#",
    language: "اللغة",
    cheap_and_smart_Solutions: "الحل الأذكى والأقل تكلفة",
    // cheap_and_smart_Solutions: 'التقنية الأذكى و الأقل تكلفة',
    sign_in: "سجل دخول",
    create_account: "أنشئ حساب",
    mobile_verification: "تحقق من رقم الهاتف",
    we_will_send_you: "سنرسل لك رمز التحقق على الهاتف",
    one_time_password: "رمز التحقق",
    on_the_mobile_number: "على رقم الهاتف",
    enter_mobile_number: "أدخل رقم الهاتف",
    get_code: "أُحصل على رمز التحقق",
    code_verification: "التحقق من الرمز",
    enter_code_sent_to: "أدخل رمز التحقق المُرسل إلى",
    didnt_receive_code: "لم أحصل على رمز التحقق؟",
    resend_code: "أعد  ارسال الرمز",
    verify_proceed: "تحقق و إستمر",
    registration_details: "تسجيل البيانات",
    create_new_account: "أنشئ حساب جديد",
    first_name: "الإسم الأول",
    last_name: "إسم العائلة",
    email: "البريد الإلكتروني",
    notes_description: "لا تتردد في وصف اي تعليمات او متطلبات اخرى لديك",
    password: "كلمة المرور",
    confirm_password: "تأكيد كلمة المرور",
    customer: "عميل",
    driver: "سائق",
    enter_vehicle: "أدخل نوع الشاحنة",
    enter_vehicle_plate_no: "أدخل رقم لوحة الشاحنة",
    vehicle_name: "ماركة الشاحنة",
    vehicle_number_plate: "رقم اللوحة",
    i_agree_to_the_movaz: "أوافق على شروط الإستخدام",
    terms_and_conditions: "الشروط و الأحكام",
    eg_jhon: "e.g John",
    eg_doe: "e.g Doe",
    example_email: "example@gmail.com",
    enter_password: "أدخل كلمة المرور",
    retype_password: "أكد كلمة المرور",
    email_or_phone: "البريد الإلكتروني او رقم الهاتف",
    welcome_back: "أهلا بعودتك",
    sign_in_to_continue: "سجل دخولك للإستمرار",
    email_or_phone_971: "البريد الإلكتروني أو رقم الهاتف(971)",
    forgot_password: "نسيت كلمة المرور؟",
    Im_a_Driver: "أنا سائق",
    dont_have_an_Account: "ليس لدي حساب!",
    driver_earnings: "أرباح السائق",
    driver_rating: "تقييم السائق",
    total_payable: "إجمالي المدفوعات",
    paid_amount: "المبلغ المدفوع",
    balance: "الرصيد",
    sub_total: "إجمالي المبلغ",
    vat: "ضريبة القيمة المضافة",
    total_trips_amount: "إجمالي عدد الرحلات",
    comission_inclusive_vat: "العموله (من غير ضريبة القيمة المضافة)",
    total_balance: "إجمالي الرصيد",
    customer_signature: "توقيع العميل",
    please_sign_in_the_space_below: "من فضلك وقع أدناه",
    order_delivered: "تم توصيل طلبكم",
    order_id: "رقم الطلب",
    amount: "المبلغ",
    items_type: "نوع المنقولات",
    pickup_date: "موعد التحميل",
    pickup_earliest_date: "موعد التحميل",
    pickup_latest_date: "موعد التحميل",
    attachments: "الصور المرفقة:",
    start_trip: "إبدأ الرحلة",
    total_amount: "إجمالي المبلغ",
    amount_received: "تم إستلام المبلغ",
    change_back: "رجوع",
    continue_: "إستمر",
    cash_on_delivery: "الدفع نقدا عند التسليم",
    reached_on_pickup: "تم الوصول لعنوان التحميل",
    reached_on_delivery: "تم الوصول لعنوان الإستلام ",
    full_name: "الإسم الكامل",
    emirate: "إمارة",
    mobile: "الهاتف المحمول",
    change_password: "تغيير كلمة المرور",
    update_profile: "تحديث الملف الشخصي",
    reviews: "آراء العملاء",
    my_profile: "ملفي الشخصي",
    reviews_and_comments: "آراء و تعليقات",
    log_out: "خروج",
    history: "السجل",
    customer_paid: "تم الدفع (نقدا)",
    company_fee: "عمولة الشركة",
    your_earnings: "ربحك",
    items: "نوع الشحنة",
    vehicle: "الشاحنة",
    vehicle_registration: "تسجيل الشاحنة",
    order_process_history: "تاريخ الطلبات",
    about_us: "نبذة عنَّا",
    about_us_heading: "نبذة عن موڤاز",
    order_is_successfull: "تم تسجيل طلبكم بنجاح!",
    order_completed_message:
      "\nسنرسل عرض السعر خلال دقائق قليلة\n\n      شكرا لاستخدامكم خدماتنا!",
    back_to_home: "الصفحة الرئيسية",
    call_support: "اتصل بنا",
    email_support: "ارسل لنا عبر البريد الإلكتروني",
    cancel: "إلغاء",
    select_pickup_adddress: "تأكيد العنوان",
    select_delivery_adddress: "تأكيد العنوان",
    upload_pictures: "حمِّل صور المنقولات",
    select_pickup_date_and_time: "إختر التاريخ و الوقت",
    notes: "تعليمات",
    notes_or_instructions: "ملاحظات و تعليمات",
    request_order: "تأكيد و تتبع المسار",
    my_orders: "طلباتي",
    order_details: "تفاصيل الطلب",
    total: "إجمالي",
    process_history: "سِجِلْ الطلبات",
    payment_cards: "بطاقات الدفع",
    payment_methods: "أساليب الدفع",
    comments_reviews: "ملاحظات وآراء",
    change_your_password: "تغيير كلمة المرور",
    enter_current_password: "كلمة المرور الحالية",
    enter_new_password: "أدخل كلمة المرور الجديدة",
    new_password: "كلمة المرور الجديدة",
    confirm_new_password: "أكد كلمة المرور الجديدة",
    save_changes: "حفظ",
    order_history: "الطلبات السابقة",
    view_order: "عرض الطلب",
    support: "الدعم",
    please_provide_pin: "أدخل الرمز السري",
    please_select_emirate: "إختر الإمارة",
    mobile_already_exists:
      "رقم الهاتف مسجل بالفعل! من فضلك سجل دخولك أو نسيت كلمة المرور",
    mobile_does_not_exists: "رقم الهاتف غير مٌسجل",
    new_user_registered: "تم التسجيل بنجاح !",
    please_enter_mobile_number: "من فضلك أدخل رقم الهاتف",
    please_enter_valid_mobile_number: "من فضلك أدخل رقم هاتف صالح",
    please_enter_mobile_number_with_country_code:
      "من فضلك أدخل رقم هاتف صالح مع  رمز الدولة",
    Im_customer: "أنا عميل",
    invalid_username_or_password: "إسم المستخدم او كلمة المرور غير صحيح",
    new_order: "طلب جديد",
    on_hold: "قيد الإنتظار",
    in_process: "قيد التنفيذ",
    ready_for_dispatch: "جاهز للإرسال",
    on_the_way_for_pickup: "في الطريق لمكان التحميل",
    moving_for_Delivery: "في الطريق للتسليم",
    delivered: "تم التسليم",
    profile_updated_successfully: "تم تحديث الملف الشخصي بنجاح !",
    get_directions: "أُحصل على الإتجاهات",
    please_select_items_type: "من فضلك إختر نوع المنقولات",
    please_select_pickup_date: "من فضلك إختر تاريخ النقل",
    please_select_pickup_start_time: "من فضلك إختر وقت النقل",
    pickup: "من",
    pickup_address: "عنوان التحميل",
    dropoff_address: "عنوان التسليم",
    dispatch: "في الطريق",
    image_library: "معرض الصور",
    take_picture: "التقط صورة",
    choose_option: "حدد خياراً",
    accept: "موافق",
    track_order: "تتبع مسار الرحلة",
    status: "الحالة",
    price: "السعر",
    view_details: "التفاصيل:",
    invoice: "الفاتورة",
    connect_via_social: "وسائل التواصل الاجتماعي",
    invoice_is_downloaded: "تم تحميل الفاتورة",
    go_to_directory: "اذهب الى الملف",
    forgot_your_password: "نسيت كلمة المرور؟",
    enter_mobile_number_recover_password: "أدخل رقم الهاتف ",
    select_items_type: "إختر نوع المنقولات",
    collected_amount: "المبلغ المدفوع",
    building_street: "البناية/الشارع",
    apartment_villa: "رقم الشقة/ڤيلا",
    drop_off_details: "عنوان التسليم",
    pickup_details: "عنوان التحميل",
    upload_pictures_quote: "يرجى تحميل جميع الصور للحصول على سعر أفضل",
    comments: "ملاحظات",
    submit: "إرسال الطلب",
    completed_orders: "الطلبات المُنجَزه",
    active_orders: "طلبات قيد التنفيذ",
    password_updated_successfully: "تم تحديث كلمة المرور بنجاح",
    profile_image_updated_successfully: "تم تحميل الصورة بنجاح !",
    error_while_updating_the_image: "خطأ خلال تحميل الصورة !",
    order: "# طلب",
    cancelled: "ملغي",
    under_process: "قيد التنفيذ",
    dispatched: "قيد التوصيل",
    completed: "تم التسليم",
    requested: "قيد الإرسال",
    settings: "الإعدادات",
    portal: "المحفظة",
    orders: "الطلبات",
    view: "عرض",
    already_have_account: "هل لديك حساب؟ سجَّل دخول",
    sign_up: "أنشئ حساب",
    help: "الأسئلة المتداولة",
    order_completed: "Order Completed",
    pickup_date_and_time: "التاريخ و الوقت",
    faqs: "الأسئلة المتداولة",
    passwords_do_not_match: "كلمة المرور غير متطابقة",
    enter_name: "أدخل الإسم",
    enter_email: "أدخل البريد الإلكتروني",
    please_select_pickup_end_time: "Please Select Pickup End Time",
    accept_selection: "تأكيد",
    earliest_pickup_date: "Earliest Pickup Date",
    please_accept_terms_and_conditions: "موافق على الشروط و الأحكام",
    enter_first_name: "أدخل الإسم الأول",
    enter_last_name: "أدخل إسم العائلة",
    first_paragraph:
      "تحدد هذه الشروط والأحكام العامة للمستخدمين القواعد التي تنطبق على جميع مستخدمي Movaz Systems ApS. قد يتم النص على استثناءات لهذه الشروط والأحكام في الاتفاقيات الفردية ، والتي ستكون لها الأسبقية في أي وقت على هذه القواعد.",
    the_service_provider_is: "مقدم الخدمة هو:",
    first_condition: "مقدم الخدمة",
    movaz_system_aps: "Movaz Digital Logistics",
    support_email: "support@movaz.ae",
    about_us_first_heading: "موڤاز رائد تكنولوجيا النقل ",
    about_us_first_paragraph:
      "موڤاز هي أول منصة نقل ذكية في دولة الإمارات العربية المتحدة, توفر مزيجًا فريدًا من الحلول اللوجستية المرنة وأحدث التقنيات التي يمكنها زيادة الكفاءة وتحسين تجارب العملاء وتقليل الأثر البيئي للنقل. من خلال ربط عملائنا بشركائنا الموثوق بهم، فإننا نلبي الطلبات المتزايدة لتجارب نقل سريعة ومنخفضة التكلفة. لصالح الأعمال والمستهلكين والبيئة.",
    about_us_second_heading: "الحاجة للابتكار",
    about_us_second_paragraph:
      "عادة ما تُوُّلَّدُ الأفكار الجيدة من الصعاب اليومية التي تحتاج إلى حل، موڤاز ليست استثناءا. العيش في دبي كمغترب يأتي بمزاياه، بالإضافة إلى متاعبه, تغيير المنازل وإيجاد شركات نقل موثوقة ومحترفة ومنخفضة التكلفة من أهم هاته المتاعب. لذلك، جاءت فكرتنا كخدمة نقل عند الطلب تمكن السائقين الذين يستخدمون الشاحنات و وسائل النقل الأخرى من التواصل مع الأشخاص والشركات من خلال عمليات التسليم، بدعم التتبع الحي للمسار والحلول اللوجستية الذكية التي تقلل التكلفة والهدر.",
    about_us_third_heading: "بداية عهد جديد",
    about_us_third_paragraph:
      "الشفافية والتحكم في كيفية نقل البضائع وتسليمها هي الهدف النهائي لشركة موڤاز اتجاه عملائها، من خلال تمكين ApS (التخطيط والجدولة المتقدمة) وأنظمة التتبع المباشر، نقوم بإنشاء نموذج الأعمال الأكثر كمالًا وحداثة, الذي يوفر لعملائنا تجربة خالية من المتاعب ومنخفضة التكلفة وصديقة للبيئة.",
    about_us_fourth_heading: "خدمات موڤاز للأفراد والشركات",
    about_us_fourth_paragraph:
      "• نحن ندعم خدماتنا بأحدث تقنياتنا التي توفر الشفافية الكاملة والتحكم في الخدمات اللوجستية الخاصة بك.\n \n• لدينا سائقين على أهبة الاستعداد للمساعدة إذا لزم الأمر.\n \n • نحن نعتمد وندير جودة جميع السائقين الذين تبلغ أعمارهم 21 عامًا على الأقل ولديهم سجلات جنائية نظيفة بنسبة 100 في المائة.\n \n • يمكن لأي شخص تسجيل طلب على تطبيقنا  أو موقعنا الإلكترونيلتسليم سريع وآمن ومنخفض التكلفة مع التتبع المباشر طوال الطريق.\n \n",
    first_paragraph:
      "     تحدد هذه الشروط والأحكام العامة للمستخدمين القواعد التي تنطبق على جميع عملاء Movaz\n\n قد يتم النص على استثناءات لهذه الشروط والأحكام في الاتفاقيات الفردية ، والتي ستكون لها الأسبقية في أي وقت على هذه القواعد.",
    the_service_provider_is: "مقدم الخدمة هو:",
    first_condition: "1. مقدم الخدمة",
    movaz_system_aps: "Movaz Logistics",
    support_email: "support@movaz.ae",
    second_condition: "2. الخدمة",
    second_condition_details:
      "موڤاز هو عبارة عن منصة وتطبيق عبر الإنترنت يتوسط  بين العملاء والشركاء ، بحيث يمكن لمستخدمي موڤاز نقل البضائع في الإمارات العربية المتحدة.الغرض من خدمة موڤاز هو التأكد من أن العميل يمكنه نقل البضائع بوسائل النقل التالية:\n \n1.	دراجة نارية أو سيارة \n2.	شاحنة صغيرة أو كبيرة\n3.	عربة رفع\n4.	شاحنة تبريد\n\n االعميل هو المسؤول عن نقل البضائع في وسيلة النقل المختارة. سيتم منح الشركاء الذين تمت الموافقة عليهم من قبل موفاز الحقوق والالتزامات الناشئة عن شروط الشريك. تتيح منصة المحرك  للعميل إرسال طلب إلى الشركاء ، الذين يمكنهم بعد ذلك قبول الشحنة. بمجرد قبول الشريك للنقل المعني ، يتم تبادل المعلومات ، بما في ذلك أسماء كل من الشريك  والعميل ونوع السيارة والموقع في الوقت الفعلي والعناوين والتعليمات وما إلى ذلك.",
    third_condition: "3. التسجيل",
    third_condition_details:
      "يجب على الأشخاص الذين يرغبون في التسجيل كعملاء واستخدام منصة المحرك تقديم المعلومات التالية\n\n1.	الاسم\n2.	رقم الهاتف  المحمول والبريد الإلكتروني.\n\nيجب ألا يقل عمر العملاء عن 18 عامًا للتسجيل في موڤاز. سيتلقى  العملاء الذين قاموا بالتسجيل على منصة موڤاز, حسابًا شخصيًا بكلمة مرور. التسجيل في موڤاز شخصي ولا يجوز لأي شخص آخر غير صاحب الحساب استخدامه.",

    forth_condition: "4. نقل البضائع",
    forth_condition_details:
      "منصة موڤاز تسمح للعميل بإرسال طلب نقل إلى احد شركائنا. يمكن للعميل إرسال طلب النقل هنا والآن ، أو يمكن للعميل إدخال تاريخ ووقت النقل المطلوب.\n\
يتحمل العميل المسؤولية الكاملة للإبلاغ عن الوصف الصحيح ورقم العناصر المتعلقة بالطلب.\n\
تبرم موڤاز عقدًا مع العميل ، ثم تجعل العميل  في اتصال مع احد شركائنا عن طريق إرسال طلب  العميل إلى الشركاء في المنطقة. يفترض جمع منقولات العميل في الوقت المطلوب شرط قبول الشريك للطلب.\n\
للشركاء ، حسب تقديرهم ، الحق في قبول أو رفض طلب النقل.\n\
يمكن للعميل اختيار وضع البضائع خارج العنوان المثبت. في هذه الحالة ، يجب على العميل أن يذكر ذلك بوضوح فيما يتعلق بالطلب. عندما يتم وضع البضائع وفقًا لإشارة العميل ، يعتبر التسليم قد تم ، ويبلغ الشريك عبر التطبيق. بعد ذلك ، تعتبر مخاطر البضائع قد تم نقلها إلى العميل ، ولم تعد موڤاز مسؤولة عن المنقولات.",

    fifth_condition: "5. التسليم",
    fifth_condition_details:
      "عندما يتم تسليم المنقولات إلى المستلم الصحيح ، سيتم إخطار العميل.\n\
يلتزم  العميل بالتأكد من  أنه نفسه - أو مستلم آخر مفوَّض - موجود على العنوان الذي حدده  كمكان التسليم الصحيح في وقت وصول السائق. ومع ذلك ، لا ينطبق هذا إذا أعطى العميل موافقته على وضع البضائع في الخارج.\n\
إذا لم يكن المستلم او المفوَّض بالإستلام على العنوان الذي حدده العميل كمكان التسليم الصحيح ، يجب على السائق محاولة الاتصال بالعميل من أجل الاتفاق على شروط التسليم البديل. في هذه الحالة ، سيكون العميل ملزمًا بدفع التكاليف الإضافية المرتبطة بهذا التسليم البديل. ومع ذلك ، لا ينطبق هذا إذا أعطى العميل موافقته على وضع البضائع في الخارج.\n\
إذا لم يتمكن السائق من الاتصال العميل ، يحق للسائق وضع البضائع أمام العنوان بعد فترة انتظار مدتها 15 دقيقة في مكان التسليم. يتم اعتبار مخاطر المنقولات على مسؤولية العميل.\n\
بمجرد تسليم المنقولات ، يتعين على  العملاء تقديم توقيعهم الرقمي لتوفير إثبات رقمي للتسليم.",
    sixth_condition: "6.تصنيف السائقين",
    sixth_condition_details:
      "تستخدم موڤاز نظام تصنيف حيث يتم تصنيف السائق من قبل العميل على مقياس من 1 إلى 5 نجوم ، والذي يمثل الأداء العام للسائق على النحو التالي:6.تصنيف السائقين.\n\
1.	غير راض \n\
2.	بحاجة إلى تحسين \n\
3.	لا بأس به \n\
4.	جيد \n\
5.	ممتاز \n\
يجب على  العميل ملاحظة أن السائق الذي لا يحتفظ بمتوسط تقييم 4.5 أو أعلى سيتم إعادة تأهيله و تقييمه بواسطة موڤاز ، ويقرر بعد ذلك ما إذا كانت موڤاز ترغب في مواصلة الشراكة. سيتم استبعاد السائق من منصة موڤاز إذا لم يرغب موڤاز في مواصلة التعاون.",

    seventh_condition: "7. الدفع",
    seventh_condition_details:
      "•  المبالغ المدفوعة غير قابلة للاسترداد.\n• يجب على  العميل تزويد موڤاز بالتفاصيل الكاملة ووصف الطلب ، بما في ذلك جميع الصور / وصف الشحنة الفعلية أو أي شحنات أخرى يتم إضافتها لاحقًا. في حالة عدم القيام بذلك ، تحتفظ موڤاز بالحق في تغيير السعر وفقًا لذلك أو إلغاء الطلب\n\nيجب تقديم أي شكوى بشأن طلبات النقل التي تمت تسويتها في غضون 24 ساعة من إكتمال النقل عبر البريد الإلكتروني إلى",
    eighth_condition: "8. سياسة البيانات الشخصية",
    eighth_condition_details:
      'تقوم موڤاز بجمع ومعالجة عدد من المعلومات حول العميل ، بما في ذلك ما يتعلق بتسجيل العميل على منصة موڤاز.\n\n\
فيما يتعلق بالتسجيل ، يوافق العميل صراحة على معالجة وتخزين موڤاز للمعلومات وفقًا لـقانون حماية البيانات (2016/679) الصادر في 27 أبريل 2016 ("قانون حماية البيانات").\n\n\
موڤاز هي وحدة التحكم في معالجة البيانات الشخصية هذه وفقًا لقانون حماية البيانات.\n\n\
لا تنقل موڤاز معلومات العميل إلى شركة أخرى لأغراض تسويقية. لا تستخدم موڤاز المعلومات نيابة عن شركة أخرى لأغراض التسويق ما لم يمنح العميل موافقته الصريحة.',
    ninth_condition: "9. الإلزامات الأساسية",
    ninth_condition_details:
      "في حالة عدم امتثال العميل للشروط والأحكام، يحق لشركة موڤاز استبعاد العميل على الفور من منصة موڤاز.\n\n\
على وجه الخصوص ، يحق ل موڤاز استبعاد العميل من منصة موفاز إذا:\n\n\
1.	أظهر العميل سلوكًا عدوانيًا أو مضايقًا أو مهينًا.\n\n\
2.	لا يلتزم العميل بالقانون المعمول به ، بما في ذلك على وجه الخصوص قانون العقوبات وقانون الأسلحة النارية وقانون المخدرات.\n\n\
3.	في حالة عدم السداد.\n\
يجب على موڤاز فورًا بعد الاستثناء إخطار العميل عبر البريد الإلكتروني إلى عنوان البريد الإلكتروني المرتبط بالمستخدم. لكن موڤاز ليست ملزمة بتبرير الاستبعاد.",

    tenth_condition: "10. بطاقات الهدايا و كوپونات الخصم",
    tenth_condition_details:
      "يمكن لـ موڤاز توفير بطاقات هدايا أو كوپونات خصم تُستخدم كمقابل للدفع لـ موڤاز، على سبيل المثال فيما يتعلق بالرسوم. يمكن استخدام بطاقة الهدايا لتغطية دفعة كاملة أو جزئية ، بينما تقلل قسيمة الخصم المبلغ الذي يتعين على العميل دفعه مقابل معاملة معينة.\n\n\
بطاقات الهدايا أو قسائم الخصم لا تقلل من المبلغ الذي يتلقاها السائق، حيث أن الفرق بين المبلغ قبل وبعد استخدام بطاقة الهدايا أو كوپون الخصم يتم رده من قبل موڤاز.\n\n\
لا يمكن استبدال بطاقات الهدايا أو كوپونات الخصم في حالة الضياع أو السرقة ولا يمكن استخدامها بعد تاريخ انتهاء الصلاحية المحتمل.",

    eleventh_condition: "11. إخلاء المسؤولية وحدودها",
    eleventh_condition_details:
      "استخدام منصة موڤاز هو على مسؤولية العميل.\n\
المعلومات والتوصيات التي يتلقاها العميل على منصة موڤاز هي لأغراض إعلامية فقط ولا تشكل نصائح.\n\
موڤاز ليست مسؤولة عما يلي:\n\
1.	محتوى غير دقيق أو أخطاء في منصة موڤاز، مثل أخطاء الكتابة أو الوظائف غير المقصودة.\n\
2.	الإصابة الشخصية أو تلف الممتلكات الذي يحدث في وقت لا تعتبر فيه البضائع في حيازة موڤاز.\n\
3.	سلوك أو أفعال الشركاء أو العملاء الآخرين.\n\
4.	لا تتحمل موڤاز اية مسؤولية عن بضائع تمت مصادرتها أو حجزها, تم إزالتها أو إتلافها من قبل الشرطة أو سلطات الجمارك أو غيرها من الوكالات الحكومية من الأصل إلى الوجهة. التمزق و التدهور الطبيعي أو التدريجي والتغيرات التي تسببها الظروف الجوية وأنواع العفن الأخرى والصدأ و الإصابة الأخرى.\n\
5.	نحن لسنا مسؤولين أيضًا عن أي تأخير في التوصيل لسبب مثل: الطقس أو الحوادث البيئية أو أي عطل في الآلات.\n\
6.	يتحمل المستخدمون و الشركاء وحدهم مسؤولية فحص العناصر قبل الاستلام و/أو أي أضرار قد تحدث أثناء النقل.",

    tweleveth_condition: "12. تعديل الشروط والأحكام",
    tweleveth_condition_details:
      "يجوز لـ موڤاز في أي وقت و بدون إشعار مسبق تغيير شروط العمل هذه وإيقاف الخدمة عن طريق إخطار العميل عبر البريد الإلكتروني إلى عنوان البريد الإلكتروني المرتبط بالعميل.\n\n\
في حالة حدوث تغييرات في هذه الشروط والأحكام ، سيتم إخطار العميل ، وسيعتبر أي استخدام لمنصة موڤاز من قبل العميل بعد ذلك قبولًا لهذه الشروط.",
  },
});
