const countryList = [
  { countryCode: "AF", countryDisplay: "Afghanistan" },
  { countryCode: "AL", countryDisplay: "Albania" },
  { countryCode: "DZ", countryDisplay: "Algeria" },
  { countryCode: "AS", countryDisplay: "American Samoa" },
  { countryCode: "AD", countryDisplay: "Andorra" },
  { countryCode: "AO", countryDisplay: "Angola" },
  { countryCode: "AI", countryDisplay: "Anguilla" },
  { countryCode: "AQ", countryDisplay: "Antarctica" },
  { countryCode: "AG", countryDisplay: "Antigua and Barbuda" },
  { countryCode: "AR", countryDisplay: "Argentina" },
  { countryCode: "AM", countryDisplay: "Armenia" },
  { countryCode: "AW", countryDisplay: "Aruba" },
  { countryCode: "AU", countryDisplay: "Australia" },
  { countryCode: "AT", countryDisplay: "Austria" },
  { countryCode: "AZ", countryDisplay: "Azerbaijan" },
  { countryCode: "BS", countryDisplay: "Bahamas (the)" },
  { countryCode: "BH", countryDisplay: "Bahrain" },
  { countryCode: "BD", countryDisplay: "Bangladesh" },
  { countryCode: "BB", countryDisplay: "Barbados" },
  { countryCode: "BY", countryDisplay: "Belarus" },
  { countryCode: "BE", countryDisplay: "Belgium" },
  { countryCode: "BZ", countryDisplay: "Belize" },
  { countryCode: "BJ", countryDisplay: "Benin" },
  { countryCode: "BM", countryDisplay: "Bermuda" },
  { countryCode: "BT", countryDisplay: "Bhutan" },
  { countryCode: "BO", countryDisplay: "Bolivia (Plurinational State of)" },
  { countryCode: "BQ", countryDisplay: "Bonaire, Sint Eustatius and Saba" },
  { countryCode: "BA", countryDisplay: "Bosnia and Herzegovina" },
  { countryCode: "BW", countryDisplay: "Botswana" },
  { countryCode: "BV", countryDisplay: "Bouvet Island" },
  { countryCode: "BR", countryDisplay: "Brazil" },
  {
    countryCode: "IO",
    countryDisplay: "British Indian Ocean Territory (the)",
  },
  { countryCode: "BN", countryDisplay: "Brunei Darussalam" },
  { countryCode: "BG", countryDisplay: "Bulgaria" },
  { countryCode: "BF", countryDisplay: "Burkina Faso" },
  { countryCode: "BI", countryDisplay: "Burundi" },
  { countryCode: "CV", countryDisplay: "Cabo Verde" },
  { countryCode: "KH", countryDisplay: "Cambodia" },
  { countryCode: "CM", countryDisplay: "Cameroon" },
  { countryCode: "CA", countryDisplay: "Canada" },
  { countryCode: "KY", countryDisplay: "Cayman Islands (the)" },
  { countryCode: "CF", countryDisplay: "Central African Republic (the)" },
  { countryCode: "TD", countryDisplay: "Chad" },
  { countryCode: "CL", countryDisplay: "Chile" },
  { countryCode: "CN", countryDisplay: "China" },
  { countryCode: "CX", countryDisplay: "Christmas Island" },
  { countryCode: "CC", countryDisplay: "Cocos (Keeling) Islands (the)" },
  { countryCode: "CO", countryDisplay: "Colombia" },
  { countryCode: "KM", countryDisplay: "Comoros (the)" },
  {
    countryCode: "CD",
    countryDisplay: "Congo (the Democratic Republic of the)",
  },
  { countryCode: "CG", countryDisplay: "Congo (the)" },
  { countryCode: "CK", countryDisplay: "Cook Islands (the)" },
  { countryCode: "CR", countryDisplay: "Costa Rica" },
  { countryCode: "HR", countryDisplay: "Croatia" },
  { countryCode: "CU", countryDisplay: "Cuba" },
  { countryCode: "CW", countryDisplay: "Curaçao" },
  { countryCode: "CY", countryDisplay: "Cyprus" },
  { countryCode: "CZ", countryDisplay: "Czechia" },
  { countryCode: "CI", countryDisplay: "Côte d'Ivoire" },
  { countryCode: "DK", countryDisplay: "Denmark" },
  { countryCode: "DJ", countryDisplay: "Djibouti" },
  { countryCode: "DM", countryDisplay: "Dominica" },
  { countryCode: "DO", countryDisplay: "Dominican Republic (the)" },
  { countryCode: "EC", countryDisplay: "Ecuador" },
  { countryCode: "EG", countryDisplay: "Egypt" },
  { countryCode: "SV", countryDisplay: "El Salvador" },
  { countryCode: "GQ", countryDisplay: "Equatorial Guinea" },
  { countryCode: "ER", countryDisplay: "Eritrea" },
  { countryCode: "EE", countryDisplay: "Estonia" },
  { countryCode: "SZ", countryDisplay: "Eswatini" },
  { countryCode: "ET", countryDisplay: "Ethiopia" },
  { countryCode: "FK", countryDisplay: "Falkland Islands (the) [Malvinas]" },
  { countryCode: "FO", countryDisplay: "Faroe Islands (the)" },
  { countryCode: "FJ", countryDisplay: "Fiji" },
  { countryCode: "FI", countryDisplay: "Finland" },
  { countryCode: "FR", countryDisplay: "France" },
  { countryCode: "GF", countryDisplay: "French Guiana" },
  { countryCode: "PF", countryDisplay: "French Polynesia" },
  { countryCode: "TF", countryDisplay: "French Southern Territories (the)" },
  { countryCode: "GA", countryDisplay: "Gabon" },
  { countryCode: "GM", countryDisplay: "Gambia (the)" },
  { countryCode: "GE", countryDisplay: "Georgia" },
  { countryCode: "DE", countryDisplay: "Germany" },
  { countryCode: "GH", countryDisplay: "Ghana" },
  { countryCode: "GI", countryDisplay: "Gibraltar" },
  { countryCode: "GR", countryDisplay: "Greece" },
  { countryCode: "GL", countryDisplay: "Greenland" },
  { countryCode: "GD", countryDisplay: "Grenada" },
  { countryCode: "GP", countryDisplay: "Guadeloupe" },
  { countryCode: "GU", countryDisplay: "Guam" },
  { countryCode: "GT", countryDisplay: "Guatemala" },
  { countryCode: "GG", countryDisplay: "Guernsey" },
  { countryCode: "GN", countryDisplay: "Guinea" },
  { countryCode: "GW", countryDisplay: "Guinea-Bissau" },
  { countryCode: "GY", countryDisplay: "Guyana" },
  { countryCode: "HT", countryDisplay: "Haiti" },
  { countryCode: "HM", countryDisplay: "Heard Island and McDonald Islands" },
  { countryCode: "VA", countryDisplay: "Holy See (the)" },
  { countryCode: "HN", countryDisplay: "Honduras" },
  { countryCode: "HK", countryDisplay: "Hong Kong" },
  { countryCode: "HU", countryDisplay: "Hungary" },
  { countryCode: "IS", countryDisplay: "Iceland" },
  { countryCode: "IN", countryDisplay: "India" },
  { countryCode: "ID", countryDisplay: "Indonesia" },
  { countryCode: "IR", countryDisplay: "Iran (Islamic Republic of)" },
  { countryCode: "IQ", countryDisplay: "Iraq" },
  { countryCode: "IE", countryDisplay: "Ireland" },
  { countryCode: "IM", countryDisplay: "Isle of Man" },
  { countryCode: "IL", countryDisplay: "Israel" },
  { countryCode: "IT", countryDisplay: "Italy" },
  { countryCode: "JM", countryDisplay: "Jamaica" },
  { countryCode: "JP", countryDisplay: "Japan" },
  { countryCode: "JE", countryDisplay: "Jersey" },
  { countryCode: "JO", countryDisplay: "Jordan" },
  { countryCode: "KZ", countryDisplay: "Kazakhstan" },
  { countryCode: "KE", countryDisplay: "Kenya" },
  { countryCode: "KI", countryDisplay: "Kiribati" },
  {
    countryCode: "KP",
    countryDisplay: "Korea (the Democratic Peoples Republic of)",
  },
  { countryCode: "KR", countryDisplay: "Korea (the Republic of)" },
  { countryCode: "KW", countryDisplay: "Kuwait" },
  { countryCode: "KG", countryDisplay: "Kyrgyzstan" },
  {
    countryCode: "LA",
    countryDisplay: "Lao People's Democratic Republic (the)",
  },
  { countryCode: "LV", countryDisplay: "Latvia" },
  { countryCode: "LB", countryDisplay: "Lebanon" },
  { countryCode: "LS", countryDisplay: "Lesotho" },
  { countryCode: "LR", countryDisplay: "Liberia" },
  { countryCode: "LY", countryDisplay: "Libya" },
  { countryCode: "LI", countryDisplay: "Liechtenstein" },
  { countryCode: "LT", countryDisplay: "Lithuania" },
  { countryCode: "LU", countryDisplay: "Luxembourg" },
  { countryCode: "MO", countryDisplay: "Macao" },
  { countryCode: "MG", countryDisplay: "Madagascar" },
  { countryCode: "MW", countryDisplay: "Malawi" },
  { countryCode: "MY", countryDisplay: "Malaysia" },
  { countryCode: "MV", countryDisplay: "Maldives" },
  { countryCode: "ML", countryDisplay: "Mali" },
  { countryCode: "MT", countryDisplay: "Malta" },
  { countryCode: "MH", countryDisplay: "Marshall Islands (the)" },
  { countryCode: "MQ", countryDisplay: "Martinique" },
  { countryCode: "MR", countryDisplay: "Mauritania" },
  { countryCode: "MU", countryDisplay: "Mauritius" },
  { countryCode: "YT", countryDisplay: "Mayotte" },
  { countryCode: "MX", countryDisplay: "Mexico" },
  { countryCode: "FM", countryDisplay: "Micronesia (Federated States of)" },
  { countryCode: "MD", countryDisplay: "Moldova (the Republic of)" },
  { countryCode: "MC", countryDisplay: "Monaco" },
  { countryCode: "MN", countryDisplay: "Mongolia" },
  { countryCode: "ME", countryDisplay: "Montenegro" },
  { countryCode: "MS", countryDisplay: "Montserrat" },
  { countryCode: "MA", countryDisplay: "Morocco" },
  { countryCode: "MZ", countryDisplay: "Mozambique" },
  { countryCode: "MM", countryDisplay: "Myanmar" },
  { countryCode: "NA", countryDisplay: "Namibia" },
  { countryCode: "NR", countryDisplay: "Nauru" },
  { countryCode: "NP", countryDisplay: "Nepal" },
  { countryCode: "NL", countryDisplay: "Netherlands (the)" },
  { countryCode: "NC", countryDisplay: "New Caledonia" },
  { countryCode: "NZ", countryDisplay: "New Zealand" },
  { countryCode: "NI", countryDisplay: "Nicaragua" },
  { countryCode: "NE", countryDisplay: "Niger (the)" },
  { countryCode: "NG", countryDisplay: "Nigeria" },
  { countryCode: "NU", countryDisplay: "Niue" },
  { countryCode: "NF", countryDisplay: "Norfolk Island" },
  { countryCode: "MP", countryDisplay: "Northern Mariana Islands (the)" },
  { countryCode: "NO", countryDisplay: "Norway" },
  { countryCode: "OM", countryDisplay: "Oman" },
  { countryCode: "PK", countryDisplay: "Pakistan" },
  { countryCode: "PW", countryDisplay: "Palau" },
  { countryCode: "PS", countryDisplay: "Palestine, State of" },
  { countryCode: "PA", countryDisplay: "Panama" },
  { countryCode: "PG", countryDisplay: "Papua New Guinea" },
  { countryCode: "PY", countryDisplay: "Paraguay" },
  { countryCode: "PE", countryDisplay: "Peru" },
  { countryCode: "PH", countryDisplay: "Philippines (the)" },
  { countryCode: "PN", countryDisplay: "Pitcairn" },
  { countryCode: "PL", countryDisplay: "Poland" },
  { countryCode: "PT", countryDisplay: "Portugal" },
  { countryCode: "PR", countryDisplay: "Puerto Rico" },
  { countryCode: "QA", countryDisplay: "Qatar" },
  { countryCode: "MK", countryDisplay: "Republic of North Macedonia" },
  { countryCode: "RO", countryDisplay: "Romania" },
  { countryCode: "RU", countryDisplay: "Russian Federation (the)" },
  { countryCode: "RW", countryDisplay: "Rwanda" },
  { countryCode: "RE", countryDisplay: "Réunion" },
  { countryCode: "BL", countryDisplay: "Saint Barthélemy" },
  {
    countryCode: "SH",
    countryDisplay: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { countryCode: "KN", countryDisplay: "Saint Kitts and Nevis" },
  { countryCode: "LC", countryDisplay: "Saint Lucia" },
  { countryCode: "MF", countryDisplay: "Saint Martin (French part)" },
  { countryCode: "PM", countryDisplay: "Saint Pierre and Miquelon" },
  { countryCode: "VC", countryDisplay: "Saint Vincent and the Grenadines" },
  { countryCode: "WS", countryDisplay: "Samoa" },
  { countryCode: "SM", countryDisplay: "San Marino" },
  { countryCode: "ST", countryDisplay: "Sao Tome and Principe" },
  { countryCode: "SA", countryDisplay: "Saudi Arabia" },
  { countryCode: "SN", countryDisplay: "Senegal" },
  { countryCode: "RS", countryDisplay: "Serbia" },
  { countryCode: "SC", countryDisplay: "Seychelles" },
  { countryCode: "SL", countryDisplay: "Sierra Leone" },
  { countryCode: "SG", countryDisplay: "Singapore" },
  { countryCode: "SX", countryDisplay: "Sint Maarten (Dutch part)" },
  { countryCode: "SK", countryDisplay: "Slovakia" },
  { countryCode: "SI", countryDisplay: "Slovenia" },
  { countryCode: "SB", countryDisplay: "Solomon Islands" },
  { countryCode: "SO", countryDisplay: "Somalia" },
  { countryCode: "ZA", countryDisplay: "South Africa" },
  {
    countryCode: "GS",
    countryDisplay: "South Georgia and the South Sandwich Islands",
  },
  { countryCode: "SS", countryDisplay: "South Sudan" },
  { countryCode: "ES", countryDisplay: "Spain" },
  { countryCode: "LK", countryDisplay: "Sri Lanka" },
  { countryCode: "SD", countryDisplay: "Sudan (the)" },
  { countryCode: "SR", countryDisplay: "Suriname" },
  { countryCode: "SJ", countryDisplay: "Svalbard and Jan Mayen" },
  { countryCode: "SE", countryDisplay: "Sweden" },
  { countryCode: "CH", countryDisplay: "Switzerland" },
  { countryCode: "SY", countryDisplay: "Syrian Arab Republic" },
  { countryCode: "TW", countryDisplay: "Taiwan (Province of China)" },
  { countryCode: "TJ", countryDisplay: "Tajikistan" },
  { countryCode: "TZ", countryDisplay: "Tanzania, United Republic of" },
  { countryCode: "TH", countryDisplay: "Thailand" },
  { countryCode: "TL", countryDisplay: "Timor-Leste" },
  { countryCode: "TG", countryDisplay: "Togo" },
  { countryCode: "TK", countryDisplay: "Tokelau" },
  { countryCode: "TO", countryDisplay: "Tonga" },
  { countryCode: "TT", countryDisplay: "Trinidad and Tobago" },
  { countryCode: "TN", countryDisplay: "Tunisia" },
  { countryCode: "TR", countryDisplay: "Turkey" },
  { countryCode: "TM", countryDisplay: "Turkmenistan" },
  { countryCode: "TC", countryDisplay: "Turks and Caicos Islands (the)" },
  { countryCode: "TV", countryDisplay: "Tuvalu" },
  { countryCode: "UG", countryDisplay: "Uganda" },
  { countryCode: "UA", countryDisplay: "Ukraine" },
  { countryCode: "AE", countryDisplay: "United Arab Emirates (the)" },
  {
    countryCode: "GB",
    countryDisplay:
      "United Kingdom of Great Britain and Northern Ireland (the)",
  },
  {
    countryCode: "UM",
    countryDisplay: "United States Minor Outlying Islands (the)",
  },
  { countryCode: "EN", countryDisplay: "United States of America (the)" },
  { countryCode: "UY", countryDisplay: "Uruguay" },
  { countryCode: "UZ", countryDisplay: "Uzbekistan" },
  { countryCode: "VU", countryDisplay: "Vanuatu" },
  { countryCode: "VE", countryDisplay: "Venezuela (Bolivarian Republic of)" },
  { countryCode: "VN", countryDisplay: "Viet Nam" },
  { countryCode: "VG", countryDisplay: "Virgin Islands (British)" },
  { countryCode: "VI", countryDisplay: "Virgin Islands (U.S.)" },
  { countryCode: "WF", countryDisplay: "Wallis and Futuna" },
  { countryCode: "EH", countryDisplay: "Western Sahara" },
  { countryCode: "YE", countryDisplay: "Yemen" },
  { countryCode: "ZM", countryDisplay: "Zambia" },
  { countryCode: "ZW", countryDisplay: "Zimbabwe" },
  { countryCode: "AX", countryDisplay: "Åland Islands" },
];

export default countryList;
